"""Refactor del modulo de notas

Revision ID: f79e89eea9f4
Revises: 97c1c4c4187c
Create Date: 2025-03-22 18:49:38.602979

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f79e89eea9f4"
down_revision: Union[str, None] = "97c1c4c4187c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note",
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "tag",
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "note_tag",
        sa.Column("note_uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tag_uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_uuid"],
            ["note.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_uuid"],
            ["tag.uuid"],
        ),
        sa.PrimaryKeyConstraint("note_uuid", "tag_uuid"),
    )
    op.drop_table("notes_tags_link")
    op.drop_table("tags")
    op.drop_table("notes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="notes_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="notes_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="tags_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="tags_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "notes_tags_link",
        sa.Column("note_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["note_id"], ["notes.id"], name="notes_tags_link_note_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name="notes_tags_link_tag_id_fkey"
        ),
        sa.PrimaryKeyConstraint("note_id", "tag_id", name="notes_tags_link_pkey"),
    )
    op.drop_table("note_tag")
    op.drop_table("tag")
    op.drop_table("note")
    # ### end Alembic commands ###
