"""Refactor del modelo

Revision ID: 6aabc47a37b2
Revises: f79e89eea9f4
Create Date: 2025-03-22 22:23:07.335937

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6aabc47a37b2"
down_revision: Union[str, None] = "f79e89eea9f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminder",
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    )
    op.add_column(
        "reminder",
        sa.Column(
            "user_uuid", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False
        ),
    )
    op.drop_constraint("reminder_user_id_fkey", "reminder", type_="foreignkey")
    op.create_foreign_key(None, "reminder", "users", ["user_uuid"], ["id"])
    op.drop_column("reminder", "user_id")
    op.drop_column("reminder", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminder",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    )
    op.add_column(
        "reminder",
        sa.Column(
            "user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint("reminder_user_uuid_fkey", "reminder", type_="foreignkey")
    op.create_foreign_key(
        "reminder_user_id_fkey", "reminder", "users", ["user_id"], ["id"]
    )
    op.drop_column("reminder", "user_uuid")
    op.drop_column("reminder", "uuid")
    # ### end Alembic commands ###
