"""Se elimino el campo de content

Revision ID: 98cbf4ad4237
Revises: abf078c303e7
Create Date: 2025-03-14 11:08:06.629957

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98cbf4ad4237"
down_revision: Union[str, None] = "abf078c303e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reminder", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminder",
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
