"""Se arreglo la tabla de inventory

Revision ID: 97c1c4c4187c
Revises: 98cbf4ad4237
Create Date: 2025-03-19 12:56:15.435415

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97c1c4c4187c"
down_revision: Union[str, None] = "98cbf4ad4237"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory",
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.drop_table("inventory_item")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_item",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("product_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("expiration_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("updated_at", sa.DATE(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="inventory_item_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="inventory_item_pkey"),
    )
    op.drop_table("inventory")
    # ### end Alembic commands ###
