"""Refactor del nombre de las tablas

Revision ID: 2b809bb66e73
Revises: 6aabc47a37b2
Create Date: 2025-03-22 23:53:05.428704

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b809bb66e73"
down_revision: Union[str, None] = "6aabc47a37b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop all foreign key constraints
    op.drop_constraint("inventory_user_uuid_fkey", "inventory", type_="foreignkey")
    op.drop_constraint("note_user_uuid_fkey", "note", type_="foreignkey")
    op.drop_constraint("reminder_user_uuid_fkey", "reminder", type_="foreignkey")
    op.drop_constraint("tag_user_uuid_fkey", "tag", type_="foreignkey")

    # Create the new user table
    op.create_table(
        "user",
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("account_verified", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)

    # Copy data from the old users table to the new user table
    op.execute(
        """
    INSERT INTO "user" (
        uuid,
        email,
        password,
        first_name,
        last_name,
        birth_date,
        phone,
        account_verified,
        is_deleted,
        created_at,
        updated_at
    )
    SELECT
        id,
        email,
        password,
        first_name,
        last_name,
        birth_date,
        phone,
        account_verified,
        is_deleted,
        created_at,
        updated_at
    FROM users;
    """
    )

    # Drop the old users table and its index
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")

    # Create the new foreign key constraints
    op.create_foreign_key(None, "inventory", "user", ["user_uuid"], ["uuid"])
    op.create_foreign_key(None, "note", "user", ["user_uuid"], ["uuid"])
    op.create_foreign_key(None, "reminder", "user", ["user_uuid"], ["uuid"])
    op.create_foreign_key(None, "tag", "user", ["user_uuid"], ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tag_user_uuid_fkey", "tag", type_="foreignkey")
    op.create_foreign_key("tag_user_uuid_fkey", "tag", "users", ["user_uuid"], ["id"])
    op.drop_constraint("reminder_user_uuid_fkey", "reminder", type_="foreignkey")
    op.create_foreign_key(
        "reminder_user_uuid_fkey", "reminder", "users", ["user_uuid"], ["id"]
    )
    op.drop_constraint("note_user_uuid_fkey", "note", type_="foreignkey")
    op.create_foreign_key("note_user_uuid_fkey", "note", "users", ["user_uuid"], ["id"])
    op.drop_constraint("inventory_user_uuid_fkey", "inventory", type_="foreignkey")
    op.create_foreign_key(
        "inventory_user_uuid_fkey", "inventory", "users", ["user_uuid"], ["id"]
    )
    op.create_table(
        "users",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("birth_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "account_verified",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
